version: '3.8'

services:
  # PostgreSQL データベース
  postgres:
    image: postgres:15
    container_name: mr_alignment_postgres
    environment:
      POSTGRES_DB: mr_alignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - mr_alignment_network

  # PHP + Laravel バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mr_alignment_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: mr_alignment
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - mr_alignment_network
    command: ["/usr/local/bin/docker-entrypoint.sh"]

  # React + Vite フロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mr_alignment_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - mr_alignment_network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"

  # pgAdmin（PostgreSQL管理ツール）
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mr_alignment_pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - mr_alignment_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  mr_alignment_network:
    driver: bridge
